# Generated by Django 4.1.1 on 2022-09-30 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('social_link', models.CharField(max_length=200)),
                ('avatar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('cover', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.author')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('img_url', models.CharField(max_length=200)),
                ('yandex_market_link', models.CharField(max_length=200)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kits.kit')),
            ],
        ),
    ]
