# Generated by Django 4.1.1 on 2022-09-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='question_text',
        ),
    ]
