# Generated by Django 4.1.1 on 2022-10-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0003_alter_product_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='cover',
            field=models.FileField(upload_to=''),
        ),
    ]
