# Generated by Django 4.1.1 on 2022-10-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0004_alter_kit_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='cover',
            field=models.FileField(upload_to='static'),
        ),
    ]
