# Generated by Django 4.1.1 on 2022-10-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0005_alter_kit_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(upload_to='static'),
        ),
    ]
