# Generated by Django 4.1.1 on 2022-10-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0006_alter_author_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='static'),
        ),
    ]
