# Generated by Django 4.1.1 on 2022-10-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0007_kit_hero_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(upload_to='static'),
        ),
    ]
