# Generated by Django 4.1.1 on 2022-10-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0008_alter_product_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('class_addon', models.CharField(max_length=200)),
            ],
        ),
    ]
