# Generated by Django 4.1.1 on 2022-10-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='static'),
        ),
    ]
