# Generated by Django 4.1.1 on 2022-10-01 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0010_author_hero_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kit',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kits.tag'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kits.author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kits.kit'),
        ),
    ]
