# Generated by Django 4.1.1 on 2022-10-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0011_author_pro_kit_tag_alter_kit_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(max_length=255, upload_to='static'),
        ),
    ]
