# Generated by Django 4.1.1 on 2022-10-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0012_alter_product_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date hit')),
                ('ip', models.CharField(max_length=15)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kits.kit')),
            ],
        ),
    ]
