# Generated by Django 4.1.1 on 2022-11-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0014_kit_class_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='other_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
