# Generated by Django 4.1.1 on 2022-11-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0015_product_other_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(upload_to='user_uploaded_static'),
        ),
        migrations.AlterField(
            model_name='author',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='user_uploaded_static'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='cover',
            field=models.FileField(upload_to='user_uploaded_static'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='user_uploaded_static'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(max_length=255, upload_to='user_uploaded_static'),
        ),
    ]
