# Generated by Django 4.1.1 on 2022-11-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kits', '0016_alter_author_avatar_alter_author_hero_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.FileField(upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='author',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='authors'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='cover',
            field=models.FileField(upload_to='kits'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='hero_cover',
            field=models.FileField(default='static/1500x500.png', upload_to='kits'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.FileField(max_length=255, upload_to='products'),
        ),
    ]
